# Generated by Django 2.1.8 on 2020-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200628_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_lat',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='input_lon',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
