# Generated by Django 2.1.8 on 2020-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200629_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_lat',
            field=models.DecimalField(decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='input_lon',
            field=models.DecimalField(decimal_places=20, max_digits=20, null=True),
        ),
    ]
