# Generated by Django 2.1.8 on 2020-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200629_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='input_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
