# Generated by Django 2.1.8 on 2020-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200630_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
