# Generated by Django 2.1.8 on 2020-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200730_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
