# Generated by Django 2.1.8 on 2020-07-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_report_filter_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='filter_date',
            new_name='input_time',
        ),
    ]
