# Generated by Django 2.1.8 on 2020-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200730_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='input_date',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='input_time',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
